### ISSUE TITLE
Дописать парсер для городских номеров Казахстана

### ISSUE THREAD

**Issue by akafist** [66ru/phonecodes#12]
Парсер не парсит сейчас городские номера, нужно доделать. http://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D0%BB%D0%B5%D1%84%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BB%D0%B0%D0%BD_%D0%BD%D1%83%D0%BC%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B8_%D0%9A%D0%B0%D0%B7%D0%B0%D1%85%D1%81%D1%82%D0%B0%D0%BD%D0%B0

**Comment by codecure** [comment]
Городские номера взял с сервиса http://spravkaru.net/kazahstan/codes/

https://github.com/mediasite/phonecodes/commit/a6d9a28776fb5dc1c61ce70ec0ba108626639319
https://github.com/mediasite/phonecodes/commit/56eaba598d281f64a38e66f60b224bdee3453bc6
https://github.com/mediasite/phonecodes/commit/50bb96f87a717f779d61002fca64c623c992f68e
