### ISSUE TITLE
Не только Россия

### ISSUE THREAD

**Issue by ramm** [66ru/phonecodes#9]
- В ответ добавить поле с названием страны
- То что сейчас парсится — Российская Федерация

**Comment by codecure** [comment]
Предлагаю не добавлять в ответ, а добавить страну в клиента в самом сервисе и организовать всю логику тут же ( например, проверка страны клиента и выборка из базы нужных записей для валидации). А пользователям (типа доски) не нужно будет думать о стране, а только знать свой ключ.

**Comment by ramm** [comment]
Это усложняет логику на стороне сервиса и не совсем понятно для чего.
Ты правда считаешь, что проще реализовать логику в доске, нежели здесь? Настраивать конфиг придется одинаково, а логики меньше сделать именно на клиенте.

В случае с доской — это просто ЕЩЕ ОДИН `if` в уже существующей проверке.

**Comment by codecure** [comment]
Да уж, я спросонья спутал с сервисом подписок (https://github.com/mediasite/subscriberss/blob/master/subscribe/models.py#L173). 
Здесь такого нет, прошу прощения.
Проще, конечно, добавить страну в поле ответа.
